GET http://localhost:5000
###

POST http://localhost:5000/signup
Content-Type: application/json

{
    "username": "apkarjun",
    "password": "apk"
}
###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "apkarjun",
    "password": "apk"
}
###

GET http://localhost:5000/users
###

GET http://localhost:5000/user/1
###

POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "Subash",
    "gender": "Male",
    "mobile": "8015298158",
    "email": "scb1212@gmail.com",
    "dob": "25/03/2000"
}
###

DELETE http://localhost:5000/user/1
###

PUT http://localhost:5000/user/1
Content-Type: application/json

{
    "name": "scb",
    "gender": "Male",
    "mobile": "8015298158",
    "email": "scb1212@gmail.com",
    "dob": "25/03/2000"
}